[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app.server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8000"