# Generated by Django 5.2.6 on 2025-09-06 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='ID del usuario (puede ser anónimo)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del usuario')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales')),
                ('encrypted', models.BooleanField(default=False, help_text='Si el contenido está encriptado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user_id'], name='conversatio_user_id_0d3af7_idx'), models.Index(fields=['ip_address'], name='conversatio_ip_addr_68c9f1_idx'), models.Index(fields=['started_at'], name='conversatio_started_0026ec_idx'), models.Index(fields=['closed_at'], name='conversatio_closed__bbfb90_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('conversation_started', 'Conversación Iniciada'), ('conversation_closed', 'Conversación Cerrada'), ('message_sent', 'Mensaje Enviado'), ('message_received', 'Mensaje Recibido'), ('user_login', 'Usuario Logueado'), ('user_logout', 'Usuario Deslogueado'), ('api_call', 'Llamada API'), ('error_occurred', 'Error Ocurrido'), ('security_event', 'Evento de Seguridad'), ('rate_limit_exceeded', 'Límite de Velocidad Excedido')], max_length=50)),
                ('actor', models.CharField(help_text='Hash del user_id o identificador del actor', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento (sin PII)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(help_text='IP enmascarada para auditoría', max_length=50)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='conversations.conversation')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='audit_logs_event_f18115_idx'), models.Index(fields=['actor'], name='audit_logs_actor_eb54d4_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'), models.Index(fields=['conversation'], name='audit_logs_convers_102330_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20)),
                ('content', models.TextField(help_text='Contenido del mensaje (puede estar encriptado)')),
                ('tokens', models.PositiveIntegerField(default=0, help_text='Número de tokens utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_encrypted_content', models.TextField(blank=True, help_text='Contenido encriptado', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'), models.Index(fields=['role'], name='messages_role_8be1df_idx'), models.Index(fields=['created_at'], name='messages_created_919c58_idx')],
            },
        ),
    ]
